### ISSUE TITLE
Cannot get Eclipse to come up

### ISSUE THREAD

**Issue by sualeh** [martinprobson/vagrant-dev-machine#1]
@martinprobson - thanks for an excellent Vagrant script, neatly laid out and structured. I usually have issues with installing a good window manager, and you have made that work for me. (I have forked your project at https://github.com/sualeh/vagrant-dev-machine) I am having trouble getting Eclipse to come up, and Firefox/ Chromium too. I am not able to see what could be going on. 

Here is what I do:
```shell
$ ~/eclipse/eclipse &
```

and I get

```
[1] 2191
[1] + Exit 1         ~/eclipse/eclipse
```

Any ideas?

**Comment by sualeh** [comment]
`export DISPLAY="127.0.0.1:10.0"` took me a liitle further. However, now I get an Eclipse configuration log message with an SWT error.

**Comment by martinprobson** [comment]
Hi Sualeh,

There seems to be some kind of version conflict with the ubuntu/1604 base box and XFCE4 which is making it unstable. I have changed the vagrant script so it is now based on a debian/stretch64 base and this seems to be working better. Please try and let me know if it works better for you,

Regards,
Martin

**Comment by martinprobson** [comment]
Please use release debian-release.

**Comment by sualeh** [comment]
Thanks! I will try it out and let you know.

**Comment by sualeh** [comment]
Works! Thanks!
